language: java

dist: trusty

sudo: required

os:
    - linux
    - osx

jdk:
    - openjdk11

addons:
    sonarcloud:
        organization: "powsybl-ci-github"
        token:
            secure: ${SONAR_TOKEN}

script:
    - mvn clean verify -Pjacoco coveralls:report sonar:sonar
